### ISSUE TITLE
Fetching Data

### ISSUE THREAD

**Issue by msgoussi** [leonawicz/eia#8]
Dear Mr. Matthew,
Greetings.
I am writing to you seeking advice.

- Let say i want data on "Petroleum and other liquids production" Annually per country, 
library(tidyverse)
library(eia)
data_ser <- eia_cats(2134915) %>%
  .[["childseries"]] %>%
  filter(grepl("INTL.53-1-.*-TBPD.A", series_id ))

y <- data_ser %>%
  pull(series_id) %>%
  .[1:100] %>% # since API can get 100 series max

  eia_series(., start = 1990)

I am wondering if this is the right way of getting data or there is a better way.

- how can i get country names, or abbreviations, or iso2 using your package in order to use as region parameter in eia_geoset function.

**Comment by leonawicz** [comment]
Hi,

For a lot of data I have looked at, the results that come back via the series endpoint or the geoset endpoint are sometimes very much the same.

For example:
```
eia_geoset("INTL.53-1-TBPD.A", c("ABW", "BEN"))
eia_series(c("INTL.53-1-ABW-TBPD.A", "INTL.53-1-BEN-TBPD.A"))
```

I intend to add more helper functions in the future that can assist with things like this. It's not always easy to plan because there is so much in the API and everyone has different use cases.

Something that may be helpful for you for the time being is the `ISOcodes` package. Provide the Alpha 3 codes to the `region` argument of `eia_geoset`.
```
library(ISOcodes)
head(ISO_3166_1)
eia_geoset("INTL.53-1-TBPD.A", ISO_3166_1$Alpha_3)
```

**Comment by msgoussi** [comment]
Thanks for replying. 
eia_geoset("INTL.53-1-TBPD.A", "WORL") is not working 

while 
eia_geoset("INTL.53-1-TBPD.A", "WLD") 

eia_series(c("INTL.53-1-WORL-TBPD.A"))
http://api.eia.gov/series/?api_key=xxxx&series_id=INTL.53-1-WORL-TBPD.A is working fine.

As you can see, World is written in two different ways.

**Comment by leonawicz** [comment]
I can't help you there. That's just looks like inconsistency in the EIA API itself. Looks like WLD is clearly their region code, but they didn't use it in their series ID. Even the series result for the WORL series ID says WLD is the region ID.

I'd expect to find more inconsistencies like that the more you use their API. It's far from perfect. And at least in terms these kind of inconsistencies, not very well documented either.

**Comment by msgoussi** [comment]
Thanks a lot
